### PR TITLE
dependabot: add auto updating submodules

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Hi,

Is there something i needed to add?

For the PR to get merged?

**Comment by bedapisl** [comment]
I would like to hear some reasoning why this should be added, why do you want these changes merged. 

Also I am not a fan of automated pull requests, which would be added by your MR. I am not saying I will never allow anything like that, but I don't see a reason for it right now.

**Comment by baseplate-admin** [comment]
Alright, Lemme start by saying, i am sorry i didnot communicate clearly.

Here's my reasoning behind the chagne:
1. `dependabot` automatically updates submodules. We can add tests to our current module and see if anything breaks against new versions of `pybind11`.
2. `pybind11` has a lot of [improvements](https://pybind11.readthedocs.io/en/stable/changelog.html#version-2-10-4-mar-16-2023) compared to the version the project is using.
3. Would make life easier if we use github actions to automate publishing against new versions of python ( you dont have to do manual compilations of files and such )

**Comment by bedapisl** [comment]
Ok, maybe this is a good idea, I can try this. I will merge your MR and see how it will work. If it will be causing some problems, I can always remove it.

**Comment by baseplate-admin** [comment]
Thank you :D

**Comment by baseplate-admin** [comment]
Hey maybe we should change the frequency from `daily` to `monthly`

https://github.com/bedapisl/fast-colorthief/blob/b7899343e7c51bb556f17a4868e5d85be4f3c95d/.github/dependabot.yml#L12
https://github.com/bedapisl/fast-colorthief/blob/b7899343e7c51bb556f17a4868e5d85be4f3c95d/.github/dependabot.yml#L18

**Pull request merged**
